### ISSUE TITLE
Gateway Measurements: Helia

### ISSUE THREAD

**Issue by whizzzkid** [protocol/network-measurements#58]
Corresponding Helia Issue: https://github.com/ipfs/helia/issues/275

```[tasklist]
### Tasks
- [ ] Build a helia-docker container: https://github.com/whizzzkid/helia-docker/pull/1
- [ ] Run Gateway measurment tests for helia-node in docker.
- [ ] Publish results on https://probelab.io/ipfsgateways/
```

As discussed with @dennis-tra.

**Comment by dennis-tra** [comment]
I have just prepared everything to have Helia running in/with our Tiros experiment to test website retrieval performance:

- Infrastructure changes: https://github.com/plprobelab/probelab-infra/pull/75
- Website changes: https://github.com/plprobelab/website/pull/80
- Website deploy preview: [link](https://deploy-preview-80--idyllic-dieffenbachia-466fef.netlify.app/websites/)
- For now, I have added Helia data only to this one graph: [link](https://deploy-preview-80--idyllic-dieffenbachia-466fef.netlify.app/websites/#websites-http-comparison-ttfb-p90) (doesn’t show any helia data yet because we don’t have any)
- Updated [Grafana Dashboard](https://protocollabs.grafana.net/d/GpwxraxVk/tiros-ops?orgId=1&from=now-6h&to=now&var-region=eu-central-1&var-ipfs_impl=helia&var-ipfs_version=v2.0.3)
